//
//  SKPhysicsContact+HelperMethods.h
//  Fish-Eat-Fish World
//
//  Created by Aleksander Makedonski on 6/8/17.
//  Copyright © 2017 AlexMakedonski. All rights reserved.
//

#import <SpriteKit/SpriteKit.h>

@interface SKPhysicsContact (HelperMethods)

typedef void(^ContactHandler)(void);
typedef void(^OtherBodyContactHandler)(SKPhysicsBody*);

+(void) executeContactHandlersForContactObject: (SKPhysicsContact*) contact;

+(NSArray<ContactHandler>*)allContactHandlersForContact:(SKPhysicsContact*)contact;

+ (ContactHandler) contactHandlerForContact:(SKPhysicsContact*)contact withReferenceCategoryBitmask:(int32_t)referenceCategoryBitmask withRedFishContactHandler:(OtherBodyContactHandler)redFishContactHandler withBlueFishContactHandler:(OtherBodyContactHandler)blueFishContactHandler withGreenFishContactHandler:(OtherBodyContactHandler)greenFishContactHandler withPinkFishContactHandler:(OtherBodyContactHandler)pinkFishContactHandler withOrangeFishContactHandler:(OtherBodyContactHandler)orangeFishContactHandler withPlayerContactHandler:(OtherBodyContactHandler)playerContactHandler withOrangePlantContactHandler:(OtherBodyContactHandler)orangePlantContactHandler withPurplePlantContactHandler:(OtherBodyContactHandler)purplePlantContactHandler withGreenPlantContactHandler:(OtherBodyContactHandler)greenPlantContactHandler withEelContactHandler:(OtherBodyContactHandler)eelContactHandler withBlowfishContactHandler:(OtherBodyContactHandler)blowFishContactHandler withBarrierContactHandler:(OtherBodyContactHandler)barrierContactHandler withCollectibleContactHandler:(OtherBodyContactHandler)collectibleContactHandler;

- (ContactHandler) contactHandlerWithReferenceCategoryBitmask:(int32_t)referenceCategoryBitmask withRedFishContactHandler:(OtherBodyContactHandler)redFishContactHandler withBlueFishContactHandler:(OtherBodyContactHandler)blueFishContactHandler withGreenFishContactHandler:(OtherBodyContactHandler)greenFishContactHandler withPinkFishContactHandler:(OtherBodyContactHandler)pinkFishContactHandler withOrangeFishContactHandler:(OtherBodyContactHandler)orangeFishContactHandler withPlayerContactHandler:(OtherBodyContactHandler)playerContactHandler withOrangePlantContactHandler:(OtherBodyContactHandler)orangePlantContactHandler withPurplePlantContactHandler:(OtherBodyContactHandler)purplePlantContactHandler withGreenPlantContactHandler:(OtherBodyContactHandler)greenPlantContactHandler withEelContactHandler:(OtherBodyContactHandler)eelContactHandler withBlowfishContactHandler:(OtherBodyContactHandler)blowFishContactHandler withBarrierContactHandler:(OtherBodyContactHandler)barrierContactHandler withCollectibleContactHandler:(OtherBodyContactHandler)collectibleContactHandler;

@end
